nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc(\.json)?$)
    documentation:
        servers:
            - url: http://localhost:8757
              description: API over HTTP
        info:
            title: Tool-Kit Test Assignment
            description: Тестовое приложение для Tool-Kit
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    required:
                                        - username
                                        - password
                                    properties:
                                        username:
                                            type: string
                                            example: client
                                        password:
                                            type: string
                                            example: '123'
                                    type: object
                    responses:
                        '200':
                            description: Список заявок
                            content:
                                application/json:
                                    schema:
                                        properties:
                                            token:
                                                type: string
                                        type: object
                        '401':
                            description: Ошибка авторизации
                            content:
                                application/json:
                                    schema:
                                        properties:
                                            code:
                                                description: Код ошибки
                                                type: string
                                            message:
                                                description: Описание ошибки
                                                type: string
                                        type: object