version: "3.8"

services:
    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:latest
        ports:
            - ${NGINX_HOST_HTTP_PORT}:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        container_name: ${PROJECT_NAME}-php-fpm
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/html
        links:
            - database
            - redis

    database:
        container_name: ${PROJECT_NAME}-database
        image: postgres:${POSTGRES_VERSION}-alpine
        ports:
            - ${DATABASE_HOST_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - database_data:/var/lib/postgresql/data:rw

    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:latest
        ports:
            - '${REDIS_HOST_PORT}:6379'

volumes:
    database_data:
